---
title: "Design Search Codes Analysis"
output: html_document
---

Plot number of trademark applications/registrations per year from 1986-2023.

```{r load_data}
library(data.table)
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
library(ggplot2)
library(patchwork)
library(tikzDevice)
options(tz = 'America/New_York')

case_file <- fread('/Volumes/EXTERNALHD1/csv/case_file.csv')
design_search <- fread('/Volumes/EXTERNALHD1/csv/design_search.csv')
#classification <- fread('/Volumes/EXTERNALHD1/csv/classification.csv')
intl_class <- fread('/Volumes/EXTERNALHD1/csv/intl_class.csv')
owner <- fread('/Volumes/EXTERNALHD1/csv/owner.csv')
attorney <- fread('/Volumes/EXTERNALHD1/csv/correspondent_domrep_attorney.csv')

```

```{r all_totals}

# plot data

case_file_filtered <- case_file |>
  filter((filing_dt >= '1986-01-01'), (filing_dt < '2024-01-01')) |> # removes all rows where filing_dt is NA
  mutate(year = year(filing_dt)) |>
  select(serial_no, filing_dt, registration_no, registration_dt, publication_dt, mark_draw_cd, mark_id_char, acq_dist_in, lb_use_file_in, supp_reg_in, serv_mark_in, trade_mark_in, cert_mark_in, coll_memb_mark_in, coll_serv_mark_in, coll_trade_mark_in, cert_mark_in, draw_color_cur_in, abandon_dt, reg_cancel_dt, year) |>
  arrange('filing_dt')

case_file_filtered_totals <- case_file_filtered |>
  #filter(grepl('^1+|^3+|^4+|^5+', mark_draw_cd)) |>
  group_by(year) |>
  mutate(app_total = n()) |>
  ungroup() |>
  filter(!(is.na(publication_dt))) |>
  group_by(year) |>
  mutate(pub_total = n()) |>
  select(year, app_total, pub_total) |>
  filter(!duplicated(year)) |>
  mutate(percentage_published = pub_total/app_total)
  
molten_filtered_totals <- pivot_longer(select(case_file_filtered_totals, year, pub_total, app_total), cols = c('pub_total', 'app_total'), names_to = 'variable', values_to = 'total')

```

```{r plot_all_totals}

theme_set(theme_classic())

tikz(file = './graphics/figure_1.tex', width = 4.5, height = 4)

figure_1 <- ggplot(molten_filtered_totals, aes(year, total, fill = variable)) +
  geom_col(position = position_dodge2(reverse = FALSE)) +
  labs(x = 'Year', y = 'Number') +
  scale_fill_manual(name = '', labels = c('Applications', 'Publications'), values = c('#203769', '#099999')) +
  scale_x_continuous(breaks = seq(1985, 2024, by = 5), limits = c(1985, 2024), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 900000, by = 100000), expand = c(0, 0), labels = scales::label_comma()) +
  theme(axis.title.x = element_text(vjust = -2, size = 7.5),
        axis.title.y = element_text(vjust = 3, size = 7.5),
        axis.text.x = element_text(size = 5.5),
        axis.text.y = element_text(size = 5.5),
        legend.text = element_text(size = 7.5))

figure_1
  
dev.off()
```

Plot number of nonword trademark applications/publications per year from 1986-2023.

```{r nonword_totals}

case_file_filtered_nonword_totals <- case_file_filtered |>
  filter(grepl('^2+|^6+', mark_draw_cd)) |>
  group_by(year) |>
  mutate(app_total_nontraditional = n()) |>
  ungroup() |>
  filter(grepl('^2+', mark_draw_cd)) |>
  #filter(supp_reg_in == 0) |>
  group_by(year) |>
  mutate(app_total_nonword = n()) |>
  ungroup() |>
  filter(!(is.na(publication_dt))) |>
  group_by(year) |>
  mutate(pub_total_nonword = n()) |>
  select(year, app_total_nontraditional, app_total_nonword, pub_total_nonword) |>
  filter(!duplicated(year)) |>
  mutate(percentage_nonword_published = pub_total_nonword/app_total_nonword)
  
molten_filtered_nonword_totals <- pivot_longer(select(case_file_filtered_nonword_totals, year, pub_total_nonword, app_total_nonword), cols = c('pub_total_nonword', 'app_total_nonword'), names_to = 'variable', values_to = 'total')

merged_app_totals <- full_join(case_file_filtered_totals, case_file_filtered_nonword_totals, by = 'year') |>
  select(year, app_total_nontraditional, app_total, app_total_nonword) |>
  mutate(percentage_nontraditional = app_total_nontraditional/app_total) |>
  mutate(percentage_nonword = app_total_nonword/app_total)

```

```{r plot_nonword_totals}

tikz(file = './graphics/figure_2.tex', width = 4.5, height = 4)

figure_2 <- ggplot(molten_filtered_nonword_totals, aes(year, total, fill = variable)) +
  geom_col(position = position_dodge2(reverse = FALSE)) +
  labs(x = 'Year', y = 'Number') +
  scale_fill_manual(name = '', labels = c('Applications', 'Publications'), values = c('#203769', '#099999')) +
  scale_x_continuous(breaks = seq(1985, 2024, by = 5), limits = c(1985, 2024), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 16000, by = 2000), expand = c(0, 0), labels = scales::label_comma()) +
  theme(axis.title.x = element_text(vjust = -2, size = 7.5),
        axis.title.y = element_text(vjust = 3, size = 7.5),
        axis.text.x = element_text(size = 5.5),
        axis.text.y = element_text(size = 5.5),
        legend.text = element_text(size = 7.5))

figure_2
  
dev.off()

```
`

```{r plot_nonword_percentage}

tikz(file = './graphics/figure_3.tex', width = 4, height = 3)

figure_3 <- ggplot(merged_app_totals, aes(year, percentage_nonword)) +
  geom_line(linewidth = 1.25) +
  labs(x = 'Year', y = 'Nonword Applications \n / Total Applications') +
  scale_x_continuous(breaks = seq(1985, 2025, by = 5), limits = c(1986, 2023), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0.02, 0.05, by = 0.01), limits = c(0.02, 0.05), expand = c(0, 0)) +
  theme(axis.title.x = element_text(vjust = -2, size = 7.5),
        axis.title.y = element_text(vjust = 3, size = 7.5),
        axis.text.x = element_text(size = 5.5),
        axis.text.y = element_text(size = 5.5))

figure_3

dev.off()

```

Compute aggregate stats for nonword marks:

```{r code_merge}

# merge design_search data with case_file data

df <- right_join(case_file_filtered, design_search, by = 'serial_no') |>
  filter(grepl('^2+', mark_draw_cd))
  
```

```{r code_aggregate_stats}

basic <- c('01.01.01', '01.01.02', '01.01.03', '01.01.04', '01.01.05', '01.01.06', '01.01.07', '01.01.09', '01.01.10', '01.01.11', '01.01.12', '01.01.13', '01.01.14', '01.03.03', '01.03.04', '01.05.01', '01.05.04', '01.05.25', '01.07.02', '01.07.04', '01.07.07', '01.07.08', '01.07.25', '01.09.01', '01.09.03', '01.09.05', '01.09.25', '01.11.01', '01.11.02', '01.11.25', '01.15.01', '01.15.02', '01.15.03', '01.15.04', '01.15.05', '01.15.06', '01.15.07', '01.15.08', '01.15.09', '01.15.10', '01.15.11', '01.15.12', '01.15.13', '01.15.15', '01.15.17', '01.15.18', '01.15.24', '01.15.25', '25.01.01', '25.01.25', '25.03.01', '25.03.02', '25.03.03', '25.03.04', '25.03.05', '25.03.25', '26.01.01', '26.01.02', '26.01.03', '26.01.04', '26.01.05', '26.01.06', '26.01.07', '26.01.08', '26.01.09', '26.01.11', '26.01.12', '26.01.13', '26.01.15', '26.01.16', '26.01.17', '26.01.18', '26.01.20', '26.01.21', '26.01.26', '26.01.27', '26.01.28', '26.01.29', '26.01.30', '26.01.31', '26.03.01', '26.03.02', '26.03.03', '26.03.04', '26.03.05', '26.03.07', '26.03.08', '26.03.09', '26.03.11', '26.03.12', '26.03.13', '26.03.14', '26.03.16', '26.03.17', '26.03.21', '26.03.28', '26.05.01', '26.05.02', '26.05.03', '26.05.05', '26.05.07', '26.05.08', '26.05.09', '26.05.12', '26.05.13', '26.05.14', '26.05.15', '26.05.16', '26.05.20', '26.05.21', '26.05.25', '26.05.28', '26.07.01', '26.07.02', '26.07.03', '26.07.12', '26.07.13', '26.07.14', '26.07.15', '26.07.21', '26.07.28', '26.09.01', '26.09.02', '26.09.03', '26.09.05', '26.09.07', '26.09.08', '26.09.09', '26.09.12', '26.09.13', '26.09.14', '26.09.16', '26.09.20', '26.09.21', '26.09.25', '26.09.28', '26.11.01', '26.11.02', '26.11.03', '26.11.05', '26.11.07', '26.11.08', '26.11.09', '26.11.10', '26.11.11', '26.11.12', '26.11.13', '26.11.14', '26.11.16', '26.11.20', '26.11.21', '26.11.25', '26.11.26', '26.11.27', '26.11.28', '26.13.01', '26.13.02', '26.13.03', '26.13.07', '26.13.08', '26.13.09', '26.13.12', '26.13.13', '26.13.14', '26.13.16', '26.13.21', '26.13.25', '26.13.28', '26.15.01', '26.15.02', '26.15.03', '26.15.07', '26.15.08', '26.15.09', '26.15.12', '26.15.13', '26.15.16', '26.15.20', '26.15.21', '26.15.25', '26.15.27', '26.15.28', '26.17.01', '26.17.02', '26.17.03', '26.17.04', '26.17.05', '26.17.06', '26.17.07', '26.17.08', '26.17.09', '26.17.10', '26.17.12', '26.17.25', '26.19.01', '26.19.02', '26.19.03', '26.19.04', '26.19.05', '26.19.25')

basic_stripped <- as.data.frame(as.numeric(gsub('[[:punct:]]', '', basic))) |>
  rename('design_search_cd' = 'as.numeric(gsub(\"[[:punct:]]\", \"\", basic))')

df_no_codes <- case_file |>
  arrange('filing_dt') |>
  filter(filing_dt >= '1986-01-01', filing_dt < '2024-01-01') |>
  mutate(year = year(filing_dt)) |>
  filter(grepl('^2+|^3+', mark_draw_cd)) |>
  group_by(year) |>
  mutate(total_design_apps = n()) |>
  ungroup() |>
  right_join(design_search, by = 'serial_no') |>
  select(serial_no, filing_dt, registration_no, registration_dt, publication_dt, mark_draw_cd, mark_id_char, design_search_cd, acq_dist_in, lb_use_file_in, supp_reg_in, serv_mark_in, trade_mark_in, cert_mark_in, coll_memb_mark_in, coll_serv_mark_in, coll_trade_mark_in, cert_mark_in, draw_color_cur_in, abandon_dt, reg_cancel_dt, year, total_design_apps) |>
  mutate(basic = case_when((design_search_cd %in% basic_stripped$design_search_cd) == TRUE ~ 1, TRUE ~ 0)) |>
  mutate(nonbasic = case_when((design_search_cd %in% basic_stripped$design_search_cd) == FALSE ~ 1, TRUE ~ 0)) |>
  group_by(year) |>
  mutate(total_design_codes = n()) |>
  ungroup() |>
  filter(grepl('^2+', mark_draw_cd)) |>
  group_by(serial_no) |>
  mutate(n_basic = sum(basic)) |>
  mutate(n_nonbasic = sum(nonbasic)) |>
  mutate(n = n()) |>
  filter(!duplicated(serial_no)) |>
  mutate(percentage_basic = n_basic/n) |>
  ungroup() |>
  group_by(year) |>
  mutate(ratio_basic_nonbasic = sum(n_basic)/sum(n_nonbasic)) |>
  ungroup()

mean(df_no_codes$n)
median(df_no_codes$n)

```

```{r code_per_year_stats}

df_no_codes_per_year <- df |>
  group_by(serial_no) |>
  #mutate(writing = case_when(grepl('^27+|^28+|^2901+', design_search_cd) == TRUE ~ 1, TRUE ~ 0)) |>
  #mutate(writing = max(writing)) |>
  mutate(n = n()) |>
  filter(!duplicated(serial_no)) |>
  #filter(max(writing) != '1') |>
  ungroup() |>
  group_by(year) |>
  summarise(mean = mean(n), median = median(n)) |>
  pivot_longer(cols = c('mean', 'median'), names_to = 'measure', values_to = 'value')

```

```{r plot_design_search_code_per_year_stats}

tikz(file = './graphics/figure_4.tex', width = 5, height = 3.5)

figure_4 <- ggplot(df_no_codes_per_year, aes(year, value, color = measure)) +
  geom_line(linewidth = 1.25) +
  labs(x = 'Year', y = 'Value') +
  scale_color_manual(
    name = '',
    labels = c('Per-year mean', 'Per-year median'),
    values = c('#203769', '#099999')
  ) +
  scale_x_continuous(breaks = seq(1985, 2025, by = 5), limits = c(1986, 2024), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(1.5, 4, by = 0.5), limits = c(1.5, 4), expand = c(0, 0)) +
  theme(axis.title.x = element_text(vjust = -3, size = 7.5),
        axis.title.y = element_text(vjust = 3, size = 7.5),
        axis.text.x = element_text(vjust = 0.3, angle = 45, size = 5.5),
        axis.text.y = element_text(size = 5.5),
        legend.text = element_text(size = 7.5))


figure_4
  
dev.off()

```

```{r super_calculations}

super_totals_per_year <- df |>
  filter(supp_reg_in == '0') |>
  #filter(filing_dt > '2007-01-07') |>
  mutate(writing = case_when(grepl('^27+|^28+|^2901+', design_search_cd) == TRUE ~ 1, TRUE ~ 0)) |>
  group_by(serial_no) |>
  mutate(n = n()) |>
  mutate(writing = max(writing)) |>
  ungroup() |>
  filter(!duplicated(serial_no)) |>
  filter(writing != '1') |>
  group_by(year) |>
  mutate(super5 = case_when(n > 5 ~ 1, TRUE ~ 0)) |>
  mutate(super10 = case_when(n > 10 ~ 1, TRUE ~ 0)) |>
  mutate(super15 = case_when(n > 15 ~ 1, TRUE ~ 0)) |>
  select(year, super5, super10, super15) |>
  group_by(year) |>
  mutate(super5 = sum(super5)) |>
  mutate(super10 = sum(super10)) |>
  mutate(super15 = sum(super15)) |>
  filter(!duplicated(year)) |>
  full_join(case_file_filtered_totals) |>
  full_join(case_file_filtered_nonword_totals) |>
  mutate(percentage5 = super5/app_total) |>
  mutate(percentage10 = super10/app_total) |>
  mutate(percentage15 = super15/app_total)
  

```

```{r super_plots}

tikz(file = './graphics/figure_5.tex', width = 5.75, height = 3.5)

figure_5.1 <- ggplot(super_totals_per_year, aes(year, super5)) +
  geom_col(fill = '#203769') +
  labs(x = 'Year', y = 'Number of Applications with $>$ 5 Codes') +
  scale_x_continuous(breaks = seq(1985, 2023, by = 5), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 3500, by = 250), expand = c(0, 0)) +
  theme(axis.title.x = element_text(vjust = -3, size = 7.5),
        axis.title.y = element_text(vjust = 3, size = 7.5),
        axis.text.x = element_text(vjust = 0.3, angle = 45, size = 5.5),
        axis.text.y = element_text(size = 5.5))

figure_5.2 <- ggplot(super_totals_per_year, aes(year, super10)) +
  geom_col(fill = '#203769') +
  labs(x = 'Year', y = 'Number of Applications with $>$ 10 Codes') +
  scale_x_continuous(breaks = seq(1985, 2023, by = 5), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 300, by = 25), expand = c(0, 0)) +
  theme(axis.title.x = element_text(vjust = -3, size = 7.5),
        axis.title.y = element_text(vjust = 3, size = 7.5),
        axis.text.x = element_text(vjust = 0.3, angle = 45, size = 5.5),
        axis.text.y = element_text(size = 5.5))
  
figure_5.3 <- ggplot(super_totals_per_year, aes(year, super15)) +
  geom_col(fill = '#203769') +
  labs(x = 'Year', y = 'Number of Applications with $>$ 15 Codes') +
  scale_x_continuous(breaks = seq(1985, 2023, by = 5), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 60, by = 5), expand = c(0, 0)) +
  theme(axis.title.x = element_text(vjust = -3, size = 7.5),
        axis.title.y = element_text(vjust = 3, size = 7.5),
        axis.text.x = element_text(vjust = 0.3, angle = 45, size = 5.5),
        axis.text.y = element_text(size = 5.5))

figure_5.1 + figure_5.2 + figure_5.3

dev.off()

```

```{r super_percentage_plot}

tikz(file = './graphics/figure_6.tex', width = 5.75, height = 3.5)

figure_6.1 <- ggplot(super_totals_per_year, aes(year, percentage5)) +
  geom_line(linewidth = 0.75) +
  labs(x = 'Year', y = 'Nonword Applications with $>$ 5 Codes\n / All Applications') +
  scale_x_continuous(breaks = seq(1985, 2023, by = 5), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0.001, 0.005, by = 0.001), limits = c(0.001, 0.005), expand = c(0, 0)) +
  theme(axis.title.x = element_text(vjust = -3, size = 7.5),
        axis.title.y = element_text(vjust = 3, size = 7.5),
        axis.text.x = element_text(vjust = 0.3, angle = 45, size = 6),
        axis.text.y = element_text(size = 6))

figure_6.2 <- ggplot(super_totals_per_year, aes(year, percentage10)) +
  geom_line(linewidth = 0.75) +
  labs(x = 'Year', y = 'Nonword Applications with $>$ 10 Codes\n / All Applications') +
  scale_x_continuous(breaks = seq(1985, 2023, by = 5), expand = c(0, 0)) +
  scale_y_continuous(labels = scales::label_number(), expand = c(0, 0)) +
  theme(axis.title.x = element_text(vjust = -3, size = 7.5),
        axis.title.y = element_text(vjust = 3, size = 7.5),
        axis.text.x = element_text(vjust = 0.3, angle = 45, size = 6),
        axis.text.y = element_text(size = 6))

figure_6.3 <- ggplot(super_totals_per_year, aes(year, percentage15)) +
  geom_line(linewidth = 0.75) +
  labs(x = 'Year', y = 'Nonword Applications with $>$ 15 Codes\n / All Applications') +
  scale_x_continuous(breaks = seq(1985, 2023, by = 5), expand = c(0, 0)) +
  scale_y_continuous(labels = scales::label_number(), expand = c(0, 0)) +
  theme(axis.title.x = element_text(vjust = -3, size = 7.5),
        axis.title.y = element_text(vjust = 3, size = 7.5),
        axis.text.x = element_text(vjust = 0.3, angle = 45, size = 6),
        axis.text.y = element_text(size = 6))

figure_6.1 + figure_6.2 + figure_6.3

dev.off()

```

Switch to focus on number of different categories of design codes:

```{r category_aggregate_stats}

df_no_categories <- df |>
  group_by(serial_no) |>
  mutate(n = n()) |>
  ungroup() |>
  mutate(category = str_sub(design_search_cd, 0, -5)) |>
  group_by(serial_no) |>
  mutate(n_category = length(unique(category))) |>
  filter(!duplicated(serial_no)) |>
  ungroup()

mean(df_no_categories$n_category)
median(df_no_categories$n_category)

```

```{r category_per_year_stats}

df_no_categories_per_year <- df_no_categories |>
  group_by(year) |>
  summarise(mean = mean(n_category), median = median(n_category))

figure_I.1 <- ggplot(df_no_categories_per_year, aes(year, mean)) +
  geom_point() +
  geom_line() +
  labs(x = 'Year', y = 'Mean Number of Categories') +
  scale_x_continuous(breaks = seq(1985, 2024, by = 5), limits = c(1985, 2024), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 5), limits = c(0, 5), expand = c(0, 0)) +
  theme_classic()

figure_I.2 <- ggplot(df_no_categories_per_year, aes(year, median)) +
  geom_point() +
  geom_line() +
  labs(x = 'Year', y = 'Median Number of Categories') +
  scale_x_continuous(breaks = seq(1985, 2024, by = 5), limits = c(1985, 2024), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 5), limits = c(0, 5), expand = c(0, 0)) +
  theme_classic()

figure_I.1 + figure_I.2

```

```{r supercat_calculations}

supercat_totals_per_year <- df_no_categories |>
  mutate(super3 = case_when(n_category > 3 ~ 1, TRUE ~ 0)) |>
  mutate(super5 = case_when(n_category > 5 ~ 1, TRUE ~ 0)) |>
  mutate(super7 = case_when(n_category > 7 ~ 1, TRUE ~ 0)) |>
  select(year, super3, super5, super7) |>
  group_by(year) |>
  mutate(super3 = sum(super3)) |>
  mutate(super5 = sum(super5)) |>
  mutate(super7 = sum(super7)) |>
  ungroup() |>
  filter(!duplicated(year)) |>
  full_join(case_file_filtered_totals) |>
  full_join(case_file_filtered_nonword_totals) |>
  mutate(percentage3 = super3/app_total) |>
  mutate(percentage5 = super5/app_total) |>
  mutate(percentage7 = super7/app_total)

```


```{r nonbasic_stats}

mean(df_no_codes$n_nonbasic)
median(df_no_codes$n_nonbasic)

```

```{r nonbasic_per_year_stats}

df_no_nonbasic_per_year <- df_no_codes |>
  group_by(year) |>
  summarise(mean = mean(n_nonbasic), median = median(n_nonbasic))

figure_I.1 <- ggplot(df_no_nonbasic_per_year, aes(year, mean)) +
  geom_point() +
  geom_line() +
  labs(x = 'Year', y = 'Mean') +
  scale_x_continuous(breaks = seq(1985, 2024, by = 5), limits = c(1985, 2024), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 5), limits = c(0, 5), expand = c(0, 0)) +
  theme_classic()

figure_I.2 <- ggplot(df_no_nonbasic_per_year, aes(year, median)) +
  geom_point() +
  geom_line() +
  labs(x = 'Year', y = 'Median') +
  scale_x_continuous(breaks = seq(1985, 2024, by = 5), limits = c(1985, 2024), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 5), limits = c(0, 5), expand = c(0, 0)) +
  theme_classic()

figure_I.1 + figure_I.2

```

```{r supernonbasic_calculations}

supernonbasic_totals_per_year <- df_no_codes |>
  mutate(super0 = case_when(n_nonbasic > 0 ~ 1, TRUE ~ 0)) |>
  mutate(super3 = case_when(n_nonbasic > 3 ~ 1, TRUE ~ 0)) |>
  mutate(super5 = case_when(n_nonbasic > 5 ~ 1, TRUE ~ 0)) |>
  select(year, super0, super3, super5) |>
  group_by(year) |>
  mutate(super0 = sum(super0)) |>
  mutate(super3 = sum(super3)) |>
  mutate(super5 = sum(super5)) |>
  ungroup() |>
  filter(!duplicated(year)) |>
  full_join(case_file_filtered_totals) |>
  full_join(case_file_filtered_nonword_totals) |>
  mutate(percentage0 = super0/app_total) |>
  mutate(percentage3 = super3/app_total) |>
  mutate(percentage5 = super5/app_total)

```

```{r basic_per_year_stats}

df_no_basic_per_year <- df_no_codes |>
  group_by(year) |>
  summarise(mean = mean(n_basic), median = median(n_basic))

figure_II.1 <- ggplot(df_no_nonbasic_per_year, aes(year, mean)) +
  geom_point() +
  geom_line() +
  labs(x = 'Year', y = 'Mean') +
  scale_x_continuous(breaks = seq(1985, 2024, by = 5), limits = c(1985, 2024), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 5), limits = c(0, 5), expand = c(0, 0)) +
  theme_classic()

figure_II.2 <- ggplot(df_no_nonbasic_per_year, aes(year, median)) +
  geom_point() +
  geom_line() +
  labs(x = 'Year', y = 'Median') +
  scale_x_continuous(breaks = seq(1985, 2024, by = 5), limits = c(1985, 2024), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, 5), limits = c(0, 5), expand = c(0, 0)) +
  theme_classic()

figure_II.1 + figure_II.2

```

```{r supernonbasic_calculations}

superbasic_totals_per_year <- df_no_codes |>
  mutate(super0 = case_when(n_basic > 0 ~ 1, TRUE ~ 0)) |>
  mutate(super3 = case_when(n_basic > 3 ~ 1, TRUE ~ 0)) |>
  mutate(super5 = case_when(n_basic > 5 ~ 1, TRUE ~ 0)) |>
  select(year, super0, super3, super5) |>
  group_by(year) |>
  mutate(super0 = sum(super0)) |>
  mutate(super3 = sum(super3)) |>
  mutate(super5 = sum(super5)) |>
  ungroup() |>
  filter(!duplicated(year)) |>
  full_join(case_file_filtered_totals) |>
  full_join(case_file_filtered_nonword_totals) |>
  mutate(percentage0 = super0/app_total) |>
  mutate(percentage3 = super3/app_total) |>
  mutate(percentage5 = super5/app_total)

```

```{r mult_aggregate_stats}

mult <- c('01.01.09', '01.01.10', '01.01.12', '01.01.13', '01.01.14', '01.03.03',  '01.15.18', '03.19.15', '05.01.10', '05.03.08', '06.03.03', '14.11.05', '22.03.02', '24.01.05', '24.09.09', '24.15.10', '26.01.13', '26.01.15', '26.01.17', '26.01.18', '26.01.30', '26.01.31', '26.03.13', '26.03.14', '26.05.13', '26.05.15', '26.05.20', '26.07.13', '26.07.14', '26.07.15', '26.09.13', '26.09.14', '26.09.20', '26.11.13', '26.11.14', '26.11.16', '26.11.20', '26.13.13', '26.13.14', '26.15.13', '26.15.20', '26.17.02', '29.05.01', '29.05.02', '29.05.03', '29.05.04', '29.05.05', '29.05.06', '29.05.07', '29.05.08', '29.05.09', '29.05.10', '29.05.11', '29.06.01', '29.06.02', '29.06.03', '29.06.04', '29.06.05', '29.06.06', '29.06.07', '29.06.08', '29.06.09', '29.06.10', '29.06.11', '29.07.01', '29.07.02', '29.07.03', '29.07.04', '29.07.05', '29.07.06', '29.07.07', '29.07.08', '29.07.09', '29.07.10', '29.07.11')

mult_stripped <- as.data.frame(as.numeric(gsub('[[:punct:]]', '', mult))) |>
  rename('design_search_cd' = 'as.numeric(gsub(\"[[:punct:]]\", \"\", mult))')

df_no_mult <- df |>
  filter(filing_dt > '2007-01-06') |>
  mutate(mult = case_when((design_search_cd %in% mult_stripped$design_search_cd) == TRUE ~ 1, TRUE ~ 0)) |>
  group_by(serial_no) |>
  mutate(n_mult = sum(mult)) |>
  filter(!duplicated(serial_no)) |>
  ungroup()

```

```{r mult_per_year_stats}

df_no_mult_per_year <- df_no_mult |>
  group_by(year) |>
  summarise(mean = mean(n_mult), median = median(n_mult))

```

```{r supermult_calculations}

supermult_totals_per_year <- df_no_mult |>
  mutate(super0 = case_when(n_mult > 0 ~ 1, TRUE ~ 0)) |>
  mutate(super3 = case_when(n_mult > 3 ~ 1, TRUE ~ 0)) |>
  mutate(super5 = case_when(n_mult > 5 ~ 1, TRUE ~ 0)) |>
  select(year, super0, super3, super5) |>
  group_by(year) |>
  mutate(super0 = sum(super0)) |>
  mutate(super3 = sum(super3)) |>
  mutate(super5 = sum(super5)) |>
  ungroup() |>
  filter(!duplicated(year)) |>
  left_join(case_file_filtered_totals) |>
  left_join(case_file_filtered_nonword_totals) |>
  mutate(percentage0 = super0/app_total) |>
  mutate(percentage3 = super3/app_total) |>
  mutate(percentage5 = super5/app_total)

```

```{r log_regression}

# using

library(tidyr)

intl_classes <- unique(intl_class$intl_class_cd)
years <- unique(df_no_codes$year)
remove <- c('2022', '2023', '2024')
years <- as.character(years[!years %in% remove])

regression_df <- df_no_codes |>
  select(-mark_id_char, -acq_dist_in, -lb_use_file_in, -serv_mark_in, -trade_mark_in, -cert_mark_in, -coll_memb_mark_in, -coll_serv_mark_in, -coll_trade_mark_in, -draw_color_cur_in) |>
  left_join(attorney, by = 'serial_no') |>
  left_join(intl_class, by = 'serial_no') |>
  mutate(registered = case_when(is.na(registration_dt) == FALSE & grepl('^0+', registration_no) == FALSE ~ 1, TRUE ~ 0)) |>
  mutate(published = case_when(is.na(publication_dt) == FALSE ~ 1, TRUE ~ 0)) |>
  filter(!grepl('2022|2023|2024', year)) |>
  mutate(bin19861990 = case_when(grepl('1986|1987|1988|1989|1990', year) == TRUE ~ 1, TRUE ~ 0)) |>
  mutate(bin19911995 = case_when(grepl('1991|1992|1993|1994|1995', year) == TRUE ~ 1, TRUE ~ 0)) |>
  mutate(bin19962000 = case_when(grepl('1996|1997|1998|1999|2000', year) == TRUE ~ 1, TRUE ~ 0)) |>
  mutate(bin20012005 = case_when(grepl('2001|2002|2003|2004|2005', year) == TRUE ~ 1, TRUE ~ 0)) |>
  mutate(bin20062010 = case_when(grepl('2006|2007|2008|2009|2010', year) == TRUE ~ 1, TRUE ~ 0)) |>
  mutate(bin20112015 = case_when(grepl('2011|2012|2013|2014|2015', year) == TRUE ~ 1, TRUE ~ 0)) |>
  mutate(bin20162020 = case_when(grepl('2016|2017|2018|2019|2020', year) == TRUE ~ 1, TRUE ~ 0)) |>
  mutate(bin2021 = 0) |>
  mutate(intl_class_yes = 1) |>
  mutate(year_yes = 1) |>
  mutate(attorney = case_when((is.na(attorney_name) == FALSE & grepl('^[0-9]+$|^$|^\\?', attorney_name)) == FALSE ~ 1, TRUE ~ 0)) |>
  pivot_wider(names_from = 'intl_class_cd', values_from = 'intl_class_yes', values_fill = 0) |>
  pivot_wider(names_from = 'year', values_from = 'year_yes', values_fill = 0) |>
  mutate('1986' = '0') |>
  group_by(serial_no) |>
  mutate(across(c('n', 'registered', 'published', all_of(intl_classes), 'bin19861990', 'bin19911995', 'bin19962000', 'bin20012005', 'bin20062010', 'bin20112015', 'bin20162020', 'bin2021', all_of(years), 'attorney'), max)) |>
  filter(!duplicated(serial_no)) |>
  ungroup()

```

```{r log_regression_models}

regression_df_2 <- regression_df_1 |>
  select(serial_no, n, registered, published, all_of(intl_classes), bin19861990, bin19911995, bin19962000, bin20012005, bin20062010, bin20112015, bin20162020, bin2021, attorney)

regression_df_3 <- regression_df_1 |>
  select(serial_no, n, registered, published, all_of(intl_classes), all_of(years), attorney)

mod1 <- glm(published ~ . - serial_no - registered, family = binomial, data = regression_df_3)

```

```{r regression_tables}
library(xtable)

table_1 <- summary(mod4)

print(xtable(head(table_1$coefficients, 2), type = "latex", caption = '{\\label{table:1} Logistic regression output (n = number of codes)}', digits = c(0, 4, 4, 4, 4)), file = "table_1.tex")

table_2 <- summary(mod2)

print(xtable(head(table_2$coefficients, 2), type = "latex", caption = '{\\label{table:1} Logistic regression output (n = number of codes)}', digits = c(0, 4, 4, 4, 4)), file = "table_2.tex")


```

```{r codes_vs_app_no_plot}

tikz(file = './graphics/figure_8.tex', width = 6.25, height = 5)

scale1 <- 10^-9

figure_8.1 <- ggplot(super_percentages_per_year, aes(year, app_total)) +
  geom_line(aes(color = 'Total Applications'), show.legend = FALSE) +
  geom_line(aes(y = percentage10/scale1, color = 'Percentage of Applications with $>$ 10 Codes'), show.legend = FALSE) +
  scale_y_continuous(sec.axis = sec_axis(~.*scale1, name = 'Nonword Applications with $>$ 10 Codes\n / All Applications'), labels = scales::label_comma()) +
  scale_x_continuous(breaks = seq(1985, 2024, by = 5), limits = c(1985, 2024), expand = c(0, 0)) +
  labs(y = 'Total Number of Applications Filed', x = 'Year') +
  scale_color_manual(values = c('#099999', '#203769')) +
  theme(axis.title.x = element_text(vjust = -3, size = 6),
        axis.title.y = element_text(vjust = 3, size = 6),
        axis.text.x = element_text(vjust = 0.3, angle = 45, size = 5),
        axis.text.y = element_text(size = 5))

scale2 <- 10^-10

figure_8.2 <- ggplot(super_percentages_per_year, aes(year, app_total)) +
  geom_line(aes(color = 'Total Applications'), show.legend = FALSE) +
  geom_line(aes(y = percentage15/scale2, color = 'Percentage of Applications with $>$ 15 Codes'), show.legend = FALSE) +
  scale_y_continuous(sec.axis = sec_axis(~.*scale2, name = 'Nonword Applications with $>$ 15 Codes\n / All Applications'), labels = scales::label_number()) +
  scale_x_continuous(breaks = seq(1985, 2024, by = 5), limits = c(1985, 2024), expand = c(0, 0)) +
  labs(y = 'Total Number of Applications Filed', x = 'Year') +
  scale_color_manual(values = c('#099999', '#203769')) +
  theme(axis.title.x = element_text(vjust = -3, size = 6),
        axis.title.y = element_text(vjust = 3, size = 6),
        axis.text.x = element_text(vjust = 0.3, angle = 45, size = 5),
        axis.text.y = element_text(size = 5))

figure_8.1 + figure_8.2

dev.off()

```

```{r df_all}

df_all <- right_join(case_file, design_search, by = 'serial_no') |>
  filter(grepl('^2+', mark_draw_cd)) |>
  filter(!(is.na(registration_dt) | grepl('^0+', registration_no))) |>
  group_by(serial_no) |>
  mutate(n = n()) |>
  filter(!duplicated(serial_no)) |>
  select(serial_no, filing_dt, registration_dt, n)

```

```{r top_ten_ever_by_codes}

top_50_ever <- head(df_all[order(df_all$n, decreasing = TRUE), ], 50)

```

```{r alt_regression_df_2}

intl_classes <- unique(intl_class$intl_class_cd)
years <- unique(df_no_codes$year)

alt_regression_df_2 <- df_no_codes |>
  left_join(attorney, by = 'serial_no') |>
  left_join(intl_class, by = 'serial_no') |>
  mutate(year_yes = 1) |>
  mutate(intl_class_yes = 1) |>
  mutate(attorney = case_when(is.na(attorney_name) == FALSE & grepl('^[0-9]+$|^$|^\\?', attorney_name) == FALSE ~ 1, TRUE ~ 0)) |>
  pivot_wider(names_from = 'intl_class_cd', values_from = 'intl_class_yes', values_fill = 0) |>
  pivot_wider(names_from = 'year', values_from = 'year_yes', values_fill = 0) |>
  group_by(serial_no) |>
  mutate(highcode = case_when(n > 5 ~ 1, TRUE ~ 0)) |>
  summarise_at(c('highcode', 'n_basic', 'n', 'total_design_apps', 'total_design_codes', intl_classes, years, 'attorney'), max) |>
  mutate('1986' = 0) |>
  ungroup()

```

```{r lm_to_control_for_time}

mod5 <- lm(n ~ . - serial_no - total_design_codes - highcode, data = alt_regression_df_2)

mod5$coefficients[is.na(mod5$coefficients)] <- 0

```

```{r logit_to_control_for_time}

mod6 <- glm(highcode ~ . - serial_no - total_design_codes - total_design_apps - n, family = binomial, data = alt_regression_df_2)

mod6$coefficients[is.na(mod6$coefficients)] <- 0

```

```{r regression_plots}

setDT(as.data.frame(mod6[['coefficients']][51:88]), keep.rownames = TRUE) |>
  rename('effect' = 'mod6[["coefficients"]][51:88]', 'year' = 'rn') |>
  ggplot(aes(year, effect)) +
  geom_point()

```

```{r no_codes_by_class}

#tikz(file = './graphics/figure_9.1.tex', width = 6.25, height = 4)

alt_regression_df_2 |>
  filter(n > 5) |>
  select(all_of(intl_classes)) |>
  apply(2, sum) |>
  as.data.frame() |>
  setDT(keep.rownames = TRUE) |>
  rename('n' = 'apply(select(filter(alt_regression_df_2, n > 5), all_of(intl_classes)), 2, sum)', 'intl_class_cd' = 'rn') |>
  left_join(case_file_filtered |>
              left_join(intl_class, by = 'serial_no') |>
              group_by(intl_class_cd) |>
              filter(grepl('^2+|^3+', mark_draw_cd)) |>
              summarise(total = n()) |>
              ungroup()) |>
  mutate(percentage = n/total) |>
  ggplot(aes(intl_class_cd, percentage)) +
  geom_bar(stat='identity') +
  labs(y = 'Number of Applications with $>$ 5 Codes', x = 'Iternational Class')

#dev.off()

```

```{r owner_analysis}

case_file |>
  filter((filing_dt >= '1986-01-01'), (filing_dt < '2024-01-01')) |> # removes all rows where filing_dt is NA
  select(serial_no, mark_draw_cd, filing_dt) |>
  left_join(owner, by = 'serial_no') |>
  group_by(own_name) |>
  #arrange(own_type_cd, .by_group = TRUE) |>
  filter(!duplicated(serial_no)) |>
  filter(grepl('^Disney[[:space:]]Enterprises', own_name)) |>
  ungroup() |>
  left_join(intl_class, by = 'serial_no')
  
  
  #group_by(intl_class_cd) |>
  #summarise(n = n())

#^Microsoft[[:space:]]Corp|^Summit[[:space:]]Entertainment|J[[:punct:]][[:space:]]Gallo[[:space:]]Winery\\b|^Societe[[:space:]]des[[:space:]]Produits[[:space:]]Nestle|^Apple[[:space:]]Inc|^JOHNSON[[:space:]][[:punct:]][[:space:]]JOHNSON|^DA[[:space:]]LIAN[[:space:]]YA[[:space:]]TU[[:space:]]TOU[[:space:]]ZI[[:space:]]ZI[[:space:]]XUN[[:space:]]YOU[[:space:]]XIAN[[:space:]]GONG[[:space:]]SI|^PK[[:space:]]Retail[[:space:]]Holdings[[:space:]]Inc|^Paisley[[:space:]]Park[[:space:]]Enterprises\\b

#df_no_codes |>
  #left_join(owner, by = 'serial_no') |>
  #filter(n > 5) |>
  #group_by(own_name) |>
  #filter(!duplicated(serial_no)) |>
  #summarise(n = n()) |>
  #slice_max(n, n = 10)

```

```{r intl_class_analysis}

df_by_intl_class <- df |>
  #filter(supp_reg_in == '0') |>
  #filter(filing_dt > '2007-01-07')
  mutate(writing = case_when(grepl('^27+|^28+|^2901+', design_search_cd) == TRUE ~ 1, TRUE ~ 0)) |>
  group_by(serial_no) |>
  filter(max(writing) != '1') |>
  mutate(n = n()) |>
  ungroup() |>
  filter(!duplicated(serial_no)) |>
  filter(n > 5) |>
  left_join(intl_class, by = 'serial_no') |>
  group_by(intl_class_cd, year) |>
  summarise(n = n()) |>
  pivot_wider(names_from = intl_class_cd, values_from = n, values_fill = 0) |>
  full_join(case_file_filtered_totals, by = 'year') |>
  mutate(across(c(2:49), ~ .x/app_total)) |>
  summarise(across(c(2:49), ~ .x[38] - .x[1])) |>
  t()
  #group_by(year)

```